### ISSUE TITLE
Can't get to run

### ISSUE THREAD

**Issue by ghost** [EmersonElectricCo/fsf#65]
Hi,

I'm on Ubuntu 18.04.2 LTS and believe I installed all dependencies. 

Testing using `./fsf_client.py ~/fsf-master/docs/Test.zip` results in the following output

`2019-09-15 16:15:37.765584 There was a problem getting data for Test.zip from 127.0.0.1 on port 5800. Error: <class 'struct.error'>`

/tmp/daemon.log contains:

`Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 571, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "./main.py", line 52, in handle
    from scanner import Scanner
  File "/home/andrejas/fsf-master/fsf-server/scanner.py", line 28, in <module>
    import processor
  File "/home/andrejas/fsf-master/fsf-server/processor.py", line 41, in <module>
    from modules import *
  File "/home/andrejas/fsf-master/fsf-server/modules/META_MACHO.py", line 24, in <module>
    import macholibre
  File "/usr/local/lib/python2.7/dist-packages/macholibre-1.1.0-py2.7.egg/macholibre/__init__.py", line 37
    def parse(macho, certs: bool=False, out=None):
                          ^
SyntaxError: invalid syntax`

Any idea what I missed?

**Comment by jxb5151** [comment]
It looks like you're macholibre module may be having a conflict with META_MACHO.py. You might try commenting this out in the dispositioner.
```
            ('ft_macho', ['META_MACHO'], False),
```

Then moving the META_MACHO.py module out of the modules directory to troubleshoot.
